[goldmark]
[goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[goldmark.parser.attribute]
block = true

[goldmark.renderer]
unsafe = true

[goldmark.extensions]
[goldmark.extensions.passthrough]
enable = true
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[highlight]
noClasses = false

[tableOfContents]
endLevel = 4
startLevel = 2
